
import polars as pl
import os
import glob

import polars as pl


class Schema(pa.DataFrameModel):
        pl.pl.datetime: pl.pl.datetime
        pl.pl.datetime_local: pl.pl.datetime
        pl.date: pl.date
        household_id: pl.String
        group_assignment: pl.String
        affects_timepoint: pl.String
        kwh_received_total: pl.Float64
        kwh_received_heatpump: pl.Float64
        kwh_received_other: pl.Float64
        kwh_returned_total: pl.Float64
        group: pl.String
        weather_id: pl.String
        installation_haspvsystem: pl.Boolean
        protocols_available: pl.Boolean
        protocols_hasmultiplevisits: pl.Boolean
        protocols_reportids: pl.String
        metadata_available: pl.Boolean
        smartmeterdata_available_15min: pl.Boolean
        smartmeterdata_available_daily: pl.Boolean
        smartmeterdata_available_monthly: pl.Boolean
        temperature_avg_daily: pl.Float64
        temperature_max_daily: pl.Float64
        temperature_min_daily: pl.Float64
        heatingdegree_sia_daily: pl.Float64
        heatingdegree_us_daily: pl.Float64
        coolingdegree_us_daily: pl.Float64
        humidity_avg_daily: pl.Float64
        precipitation_total_daily: pl.Float64
        sunshine_duration_daily: pl.Float64
        pl.pl.datetime_local_right: pl.String
        report_id: Int64
        visit_year: pl.String
        visit_pl.date: pl.date
        building_type: pl.String
        building_housingunits: pl.Float64
        building_constructionyear: pl.Float64
        building_constructionyear_interval: pl.String
        building_renovated_windows: pl.Boolean
        building_renovated_roof: pl.Boolean
        building_renovated_walls: pl.Boolean
        building_renovated_floor: pl.Boolean
        building_floorareaheated_total: pl.Float64
        building_floorareaheated_basement: pl.Float64
        building_floorareaheated_groundfloor: pl.Float64
        building_floorareaheated_firstfloor: pl.Float64
        building_floorareaheated_secondfloor: pl.Float64
        building_floorareaheated_topfloor: pl.Float64
        building_floorareaheated_additionalareasplanned: pl.Boolean
        building_floorareaheated_additionalareasplannedsize: pl.Float64
        building_residents: pl.Float64
        building_pvsystem_available: pl.Boolean
        building_pvsystem_size: pl.String
        building_electricvehicle_available: pl.String
        heatpump_installation_type: pl.String
        heatpump_installation_year: pl.Float64
        heatpump_installation_manufacturer: pl.String
        heatpump_installation_model: pl.String
        heatpump_installation_heatingcapacity: pl.Float64
        heatpump_installation_refrigerant_type: pl.String
        heatpump_installation_refrigerant_content: pl.Float64
        heatpump_installation_normpoint: pl.String
        heatpump_installation_normpoint_cop: pl.Float64
        heatpump_installation_normpoint_electricpower: pl.Float64
        heatpump_installation_normpoint_heatingpower: pl.Float64
        heatpump_installation_location: pl.String
        heatpump_installation_internetconnection: pl.Boolean
        heatpump_installation_controllernotaccessible: pl.Float64
        heatdistribution_system_radiators: pl.Boolean
        heatdistribution_system_floorheating: pl.Boolean
        heatdistribution_system_thermostaticvalve: pl.Boolean
        heatdistribution_system_buffertankavailable: pl.Boolean
        dhw_production_byheatpump: pl.Boolean
        dhw_production_byelectricwaterheater: pl.Boolean
        dhw_production_bysolar: pl.Boolean
        dhw_production_byheatpumpboiler: pl.Boolean
        dhw_byheatpump_timeinterval: pl.String
        dhw_production_typeofheating: pl.String
        dhw_production_residents: Int64
        dhw_circulation_notinuse: pl.Boolean
        dhw_circulation_bytraceheating: pl.Boolean
        dhw_circulation_bycirculationpump: pl.Boolean
        dhw_circulation_switchedbytimer: pl.Boolean
        dhw_sterilization_available: pl.String
        dhw_sterilization_active: pl.String
        heatpump_clean: pl.Boolean
        heatpump_basicfunctionsokay: pl.Boolean
        heatpump_technicallyokay: pl.Boolean
        heatpump_electricityconsumption_yearlyestimated: pl.Float64
        heatpump_electricityconsumption_categorization: pl.String
        heatpump_installation_correctlyplanned: pl.Boolean
        heatpump_installation_incorrectlyplanned_categorization: pl.String
        heatpump_airsource_airductsdistanceokay: pl.String
        heatpump_airsource_airductsfree: pl.String
        heatpump_airsource_airductscleaningrequired: pl.String
        heatpump_airsource_airductsdrainokay: pl.String
        heatpump_airsource_evaporatorclean: pl.String
        heatpump_groundsource_brinecircuit_length: pl.String
        heatpump_groundsource_brinecircuit_depth: pl.String
        heatpump_groundsource_brinecircuit_numberofholes: pl.String
        heatpump_groundsource_brinecircuit_coolingcapacity: pl.String
        heatpump_groundsource_brinecircuit_antifreezeexists: pl.Boolean
        heatpump_groundsource_currentpressure: pl.Float64
        heatpump_groundsource_currentpressure_okay: pl.Boolean
        heatpump_groundsource_currenttemperature: pl.Float64
        heatpump_groundsource_currenttemperature_okay: pl.Boolean
        heatpump_heatingcurvesetting_toohigh_beforevisit: pl.Boolean
        heatpump_heatingcurvesetting_changed: pl.Boolean
        heatpump_heatingcurvesetting_outside20_beforevisit: pl.Float64
        heatpump_heatingcurvesetting_outside0_beforevisit: pl.Float64
        heatpump_heatingcurvesetting_outsideminus8_beforevisit: pl.Float64
        heatpump_heatingcurvesetting_outside20_aftervisit: pl.Float64
        heatpump_heatingcurvesetting_outside0_aftervisit: pl.Float64
        heatpump_heatingcurvesetting_outsideminus8_aftervisit: pl.Float64
        heatpump_heatinglimitsetting_toohigh_beforevisit: pl.String
        heatpump_heatinglimitsetting_changed: pl.String
        heatpump_heatinglimitsetting_beforevisit: pl.String
        heatpump_heatinglimitsetting_aftervisit: pl.String
        heatpump_nightsetbacksetting_activated_beforevisit: pl.Boolean
        heatpump_nightsetbacksetting_activated_aftervisit: pl.Boolean
        dhw_temperaturesetting_categorization: pl.String
        dhw_temperaturesetting_changed: pl.Boolean
        dhw_temperaturesetting_beforevisit: pl.String
        dhw_temperaturesetting_aftervisit: pl.String
        dhw_storage_lastdescaling_toolongago: pl.Boolean
        dhw_storage_lastdescaling_year: pl.String
        heatdistribution_expansiontank_pressure_categorization: pl.String
        heatdistribution_expansiontank_pressure_actual: pl.String
        heatdistribution_expansiontank_pressure_target: pl.String
        heatdistribution_expansiontank_systemheight: pl.Float64
        heatdistribution_circulation_pumpstageposition_changed: pl.String
        heatdistribution_circulation_pumpstageposition_beforevisit: pl.String
        heatdistribution_circulation_pumpstageposition_aftervisit: pl.String
        heatdistribution_recommendation_insulatepipes: pl.Boolean
        heatdistribution_recommendation_installthermostaticvalve: pl.Boolean
        heatdistribution_recommendation_installrpmvalve: pl.Boolean